### PR TITLE
Read the correct amount of bits for strokeCount

### PR DESCRIPTION
**Pull request by AuspeXeu**

### CODE REVIEW

**Comment by tijmenvangulik** [comment]
Changing it to an 8 bit value means that you can only have 256 strokes. That would be a bit short race. The manuals states:
Stroke Count Lo, CSAFE_PM_GET_STROKESTATS
Stroke Count Hi,
So it is an 16 bits value and not 8. This fix can not be right. What exactly is the problem?

**Comment by AuspeXeu** [comment]
With a PM5 and the latest firmware, I get `strokeCount = 256` after the first stroke and `strokeCount = 512` after the second stroke. Which is obviously binary `1` and `10` so there seems to be something wrong with the layout of your data structure. With the above change, it correctly shows `strokeCount = 1` and `strokeCount = 2`, respectively.

**Comment by tijmenvangulik** [comment]
This may be a case of that the low and the high bytes are swapped. I have seen that with other values. Some 16 bits values are read reverse..

Tijmen

**Comment by AuspeXeu** [comment]
How did you solve this problem since changing the endianness does not work here, can you point me to a value where you already had this issue?

**Comment by tijmenvangulik** [comment]
You can test 2 combinations:

data.getUint8(ble.PM_Extra_Stroke_Data_BLE_Payload.STROKE_COUNT_HI)+data.getUint8(ble.PM_Extra_Stroke_Data_BLE_Payload.STROKE_COUNT_LO)*256

data.getUint8(ble.PM_Extra_Stroke_Data_BLE_Payload.STROKE_COUNT_LO)+data.getUint8(ble.PM_Extra_Stroke_Data_BLE_Payload.STROKE_COUNT_HI)*256

Thank you for helping making the api better.

Tijmen

**Comment by AuspeXeu** [comment]
Done. Works just fine now :)

**Comment by tijmenvangulik** [comment]
Great work!. If push your change , I will merge it.

Tijmen

**Comment by AuspeXeu** [comment]
It's already up-to-date.

**Pull request merged**
